CREATE TABLE IF NOT EXISTS public.roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  descripcion VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  correo VARCHAR(160) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL,
  rol_id SMALLINT NOT NULL REFERENCES public.roles(id),
  estado VARCHAR(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.laboratorios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  ubicacion VARCHAR(160) NOT NULL DEFAULT '',
  descripcion TEXT,
  estado VARCHAR(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  responsable_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.equipos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL UNIQUE,
  laboratorio_id BIGINT NOT NULL REFERENCES public.laboratorios(id),
  tipo VARCHAR(40) NOT NULL DEFAULT 'Otro' CHECK (tipo IN (
    'Computadora', 'Monitor', 'Teclado', 'Mouse', 'Datashow', 'Pantalla TV',
    'Aire acondicionado', 'Switch', 'Router', 'Access Point', 'UPS', 'Impresora', 'Otro'
  )),
  marca VARCHAR(80) NOT NULL DEFAULT '',
  modelo VARCHAR(100) NOT NULL DEFAULT '',
  numero_serie VARCHAR(100) NOT NULL DEFAULT '',
  numero_inventario VARCHAR(100) NOT NULL DEFAULT '',
  descripcion TEXT,
  estado VARCHAR(40) NOT NULL DEFAULT 'OPERATIVO' CHECK (estado IN (
    'OPERATIVO', 'OPERATIVO CON OBSERVACION', 'NO OPERATIVO', 'EN MANTENIMIENTO', 'FUERA DE SERVICIO'
  )),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.inspecciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  laboratorio_id BIGINT NOT NULL REFERENCES public.laboratorios(id),
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  hora_inicio TIME NOT NULL DEFAULT LOCALTIME,
  hora_fin TIME,
  observacion_general TEXT,
  resultado VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE',
  estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR' CHECK (estado IN ('BORRADOR', 'EN PROCESO', 'FINALIZADA')),
  creada_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.categorias_inspeccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  orden SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.items_inspeccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id BIGINT NOT NULL REFERENCES public.categorias_inspeccion(id) ON DELETE CASCADE,
  nombre VARCHAR(160) NOT NULL,
  orden SMALLINT NOT NULL DEFAULT 0,
  UNIQUE (categoria_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.detalle_inspeccion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspeccion_id BIGINT NOT NULL REFERENCES public.inspecciones(id),
  categoria VARCHAR(80) NOT NULL,
  item VARCHAR(160) NOT NULL,
  estado VARCHAR(20) NOT NULL CHECK (estado IN ('OPERATIVO', 'CON OBSERVACION', 'NO OPERATIVO', 'NO APLICA')),
  observacion TEXT,
  tipo_problema VARCHAR(100) NOT NULL DEFAULT '',
  prioridad VARCHAR(10) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
  equipo_id BIGINT REFERENCES public.equipos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.incidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) UNIQUE,
  laboratorio_id BIGINT NOT NULL REFERENCES public.laboratorios(id),
  equipo_id BIGINT REFERENCES public.equipos(id) ON DELETE SET NULL,
  inspeccion_id BIGINT REFERENCES public.inspecciones(id) ON DELETE SET NULL,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  tipo VARCHAR(100) NOT NULL,
  descripcion TEXT NOT NULL,
  prioridad VARCHAR(10) NOT NULL DEFAULT 'MEDIA' CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
  estado VARCHAR(24) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN (
    'PENDIENTE', 'EN REVISION', 'EN MANTENIMIENTO', 'ESPERANDO REPUESTO', 'RESUELTA'
  )),
  fecha_reporte TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_primera_atencion TIMESTAMPTZ,
  fecha_resolucion TIMESTAMPTZ,
  responsable VARCHAR(160) NOT NULL DEFAULT '',
  accion_realizada TEXT,
  diagnostico TEXT,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.historial_incidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incidencia_id BIGINT NOT NULL REFERENCES public.incidencias(id),
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id),
  estado_anterior VARCHAR(40) NOT NULL DEFAULT '',
  estado_nuevo VARCHAR(40) NOT NULL DEFAULT '',
  comentario TEXT NOT NULL,
  fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.mantenimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipo_id BIGINT NOT NULL REFERENCES public.equipos(id),
  tipo VARCHAR(12) NOT NULL CHECK (tipo IN ('PREVENTIVO', 'CORRECTIVO')),
  descripcion TEXT NOT NULL,
  fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_fin TIMESTAMPTZ,
  responsable VARCHAR(160) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADO' CHECK (estado IN ('PROGRAMADO', 'EN PROCESO', 'COMPLETADO', 'CANCELADO')),
  resultado TEXT,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.sesiones (
  token_hash CHAR(64) PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  expira_en TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_equipo_lab_activo ON public.equipos (laboratorio_id, activo);
CREATE INDEX IF NOT EXISTS idx_equipo_tipo ON public.equipos (tipo);
CREATE INDEX IF NOT EXISTS idx_inspeccion_fecha ON public.inspecciones (fecha, laboratorio_id);
CREATE INDEX IF NOT EXISTS idx_incidencia_estado ON public.incidencias (estado, fecha_reporte);
CREATE INDEX IF NOT EXISTS idx_incidencia_equipo ON public.incidencias (equipo_id, estado);
CREATE INDEX IF NOT EXISTS idx_historial_fecha ON public.historial_incidencias (incidencia_id, fecha);
CREATE INDEX IF NOT EXISTS idx_mantenimiento_equipo ON public.mantenimientos (equipo_id, fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_sesion_expira ON public.sesiones (expira_en);

INSERT INTO public.roles (nombre, descripcion) VALUES
  ('Administrador', 'Gestion general del sistema'),
  ('Coordinador Académico', 'Supervision, inventario e incidencias'),
  ('Docente', 'Inspecciones y reporte de anomalías')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.laboratorios (codigo, nombre, ubicacion, descripcion) VALUES
  ('LAB-01', 'Laboratorio 1', 'Edificio académico', 'Laboratorio de cómputo 1'),
  ('LAB-02', 'Laboratorio 2', 'Edificio académico', 'Laboratorio de cómputo 2'),
  ('LAB-03', 'Laboratorio 3', 'Edificio académico', 'Laboratorio de cómputo 3'),
  ('LAB-04', 'Laboratorio 4', 'Edificio académico', 'Laboratorio de cómputo 4'),
  ('LAB-MAC', 'Laboratorio MAC', 'Edificio académico', 'Laboratorio de equipos Mac')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.categorias_inspeccion (nombre, orden) VALUES
  ('Infraestructura', 1), ('Equipamiento', 2), ('Seguridad', 3),
  ('Orden y limpieza', 4), ('Recursos adicionales', 5)
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.items_inspeccion (categoria_id, nombre, orden)
SELECT c.id, item.nombre, item.orden
FROM (VALUES
  ('Infraestructura', 'Instalación eléctrica', 1),
  ('Infraestructura', 'Tomas eléctricas', 2),
  ('Infraestructura', 'Cableado de red', 3),
  ('Infraestructura', 'Acceso a Internet', 4),
  ('Infraestructura', 'Puertas y cerraduras', 5),
  ('Infraestructura', 'Mobiliario', 6),
  ('Infraestructura', 'Iluminación', 7),
  ('Infraestructura', 'Aire acondicionado', 8),
  ('Equipamiento', 'Equipos identificados', 1),
  ('Equipamiento', 'Computadoras en buen estado y limpias', 2),
  ('Equipamiento', 'Monitores disponibles', 3),
  ('Equipamiento', 'Teclados y mouse disponibles', 4),
  ('Equipamiento', 'Equipos organizados', 5),
  ('Seguridad', 'Normas visibles', 1),
  ('Seguridad', 'Sin cables peligrosos', 2),
  ('Seguridad', 'Extintores disponibles y vigentes', 3),
  ('Seguridad', 'Áreas despejadas', 4),
  ('Seguridad', 'Condiciones eléctricas seguras', 5),
  ('Seguridad', 'Iluminación adecuada', 6),
  ('Orden y limpieza', 'Laboratorio limpio', 1),
  ('Orden y limpieza', 'Equipos limpios', 2),
  ('Orden y limpieza', 'Mesas ordenadas', 3),
  ('Orden y limpieza', 'Pasillos despejados', 4),
  ('Orden y limpieza', 'Área general organizada', 5),
  ('Recursos adicionales', 'Pantalla TV y Datashow', 1),
  ('Recursos adicionales', 'Interruptores y equipos audiovisuales', 2),
  ('Recursos adicionales', 'Otros recursos', 3)
) AS item(categoria, nombre, orden)
JOIN public.categorias_inspeccion c ON c.nombre = item.categoria
ON CONFLICT (categoria_id, nombre) DO NOTHING;

INSERT INTO public.equipos (codigo, laboratorio_id, tipo, marca, modelo)
SELECT
  'PC-L' || CAST(SUBSTRING(l.codigo FROM 5) AS INTEGER)::TEXT || '-' || LPAD(n.numero::TEXT, 2, '0'),
  l.id, 'Computadora', 'Lenovo', 'ThinkCentre'
FROM public.laboratorios l
CROSS JOIN generate_series(1, 5) AS n(numero)
WHERE l.codigo IN ('LAB-01', 'LAB-02', 'LAB-03', 'LAB-04')
  AND NOT EXISTS (
    SELECT 1 FROM public.equipos existing
    WHERE existing.laboratorio_id = l.id
      AND existing.tipo = 'Computadora'
      AND existing.codigo IN (
        'PC-L' || CAST(SUBSTRING(l.codigo FROM 5) AS INTEGER)::TEXT || '-' || LPAD(n.numero::TEXT, 2, '0'),
        'PC-L0' || CAST(SUBSTRING(l.codigo FROM 5) AS INTEGER)::TEXT || '-' || LPAD(n.numero::TEXT, 2, '0')
      )
  )
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.equipos (codigo, laboratorio_id, tipo, marca, modelo)
SELECT 'MAC-' || LPAD(n.numero::TEXT, 2, '0'), l.id, 'Computadora', 'Apple', 'iMac'
FROM public.laboratorios l
CROSS JOIN generate_series(1, 4) AS n(numero)
WHERE l.codigo = 'LAB-MAC'
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO public.equipos (codigo, laboratorio_id, tipo, marca, modelo)
SELECT 'PROY-' || REPLACE(l.codigo, 'LAB-', '') || '-01', l.id, 'Datashow', '', ''
FROM public.laboratorios l
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.laboratorios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspecciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias_inspeccion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items_inspeccion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_inspeccion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historial_incidencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mantenimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sesiones ENABLE ROW LEVEL SECURITY;